apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: camel-hl7-gateway-configmap
data:
  application.properties: |-
    spring.datasource.url: jdbc:mysql://192.168.99.1:3306/example?autoReconnect=true&useSSL=false
